src/Entity/Race.php
<?php

namespace App\Entity;

use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\RaceRepository")
 */
class Race
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=64)
     */
    private $track;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Championship", inversedBy="races")
     */
    private $championship_id;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\TeamEntryList", mappedBy="race_id")
     * @ORM\OrderBy({"Laps" = "DESC", "result" = "ASC"})
     */
    private $teamEntryLists;

    /**
     * @ORM\Column(type="integer")
     */
    private $ambientTemp;

    /**
     * @ORM\Column(type="float")
     */
    private $cloudLevel;

    /**
     * @ORM\Column(type="float")
     */
    private $rain;

    /**
     * @ORM\Column(type="integer")
     */
    private $practice_hour;

    /**
     * @ORM\Column(type="integer")
     */
    private $practice_length;

    /**
     * @ORM\Column(type="integer")
     */
    private $qualy_hour;

    /**
     * @ORM\Column(type="integer")
     */
    private $qualy_length;

    /**
     * @ORM\Column(type="integer")
     */
    private $race_hour;

    /**
     * @ORM\Column(type="integer")
     */
    private $race_length;

    /**
     * @ORM\Column(type="datetime")
     */
    private $greenflagtime;

    /**
     * @ORM\Column(type="boolean", options={"default": false})
     */
    private $complete;

    public function __construct()
    {
        $this->teamEntryLists = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTrack(): ?string
    {
        return $this->track;
    }

    public function setTrack(string $track): self
    {
        $this->track = $track;

        return $this;
    }

    public function getChampionshipId(): ?Championship
    {
        return $this->championship_id;
    }

    public function setChampionshipId(?Championship $championship_id): self
    {
        $this->championship_id = $championship_id;

        return $this;
    }

    /**
     * @return Collection|TeamEntryList[]
     */
    public function getTeamEntryLists(): Collection
    {
        return $this->teamEntryLists;
    }

    public function addTeamEntryList(TeamEntryList $teamEntryList): self
    {
        if (!$this->teamEntryLists->contains($teamEntryList)) {
            $this->teamEntryLists[] = $teamEntryList;
            $teamEntryList->setRaceId($this);
        }

        return $this;
    }

    public function removeTeamEntryList(TeamEntryList $teamEntryList): self
    {
        if ($this->teamEntryLists->contains($teamEntryList)) {
            $this->teamEntryLists->removeElement($teamEntryList);
            // set the owning side to null (unless already changed)
            if ($teamEntryList->getRaceId() === $this) {
                $teamEntryList->setRaceId(null);
            }
        }

        return $this;
    }

    public function getAmbientTemp(): ?int
    {
        return $this->ambientTemp;
    }

    public function setAmbientTemp(int $ambientTemp): self
    {
        $this->ambientTemp = $ambientTemp;

        return $this;
    }

    public function getCloudLevel(): ?float
    {
        return $this->cloudLevel;
    }

    public function setCloudLevel(float $cloudLevel): self
    {
        $this->cloudLevel = $cloudLevel;

        return $this;
    }

    public function getRain(): ?float
    {
        return $this->rain;
    }

    public function setRain(float $rain): self
    {
        $this->rain = $rain;

        return $this;
    }

    public function getPracticeHour(): ?int
    {
        return $this->practice_hour;
    }

    public function setPracticeHour(int $practice_hour): self
    {
        $this->practice_hour = $practice_hour;

        return $this;
    }

    public function getPracticeLength(): ?int
    {
        return $this->practice_length;
    }

    public function setPracticeLength(int $practice_length): self
    {
        $this->practice_length = $practice_length;

        return $this;
    }

    public function getQualyHour(): ?int
    {
        return $this->qualy_hour;
    }

    public function setQualyHour(int $qualy_hour): self
    {
        $this->qualy_hour = $qualy_hour;

        return $this;
    }

    public function getQualyLength(): ?int
    {
        return $this->qualy_length;
    }

    public function setQualyLength(int $qualy_length): self
    {
        $this->qualy_length = $qualy_length;

        return $this;
    }

    public function getRaceHour(): ?int
    {
        return $this->race_hour;
    }

    public function setRaceHour(int $race_hour): self
    {
        $this->race_hour = $race_hour;

        return $this;
    }

    public function getRaceLength(): ?int
    {
        return $this->race_length;
    }

    public function setRaceLength(int $race_length): self
    {
        $this->race_length = $race_length;

        return $this;
    }

    public function getGreenflagtime(): ?DateTimeInterface
    {
        return $this->greenflagtime;
    }

    public function setGreenflagtime(DateTimeInterface $greenflagtime): self
    {
        $this->greenflagtime = $greenflagtime;

        return $this;
    }

    /**
     * This function obtains a formatted name to easily identify a race, with the following format:
     * Race Track - Championship Name
     * @return string String formatted to easily identify which Race it is.
     */
    public function getRaceinfo(): string
    {
        $string = "";
        $string = $string.$this->getTrack();
        $string = $string.' - '.$this->getChampionshipId()->getName();
        $string = str_replace('_2019', '', $string);
        $string = str_replace('_', ' ', $string);
        return ucwords($string);
    }

    public function getComplete(): ?bool
    {
        return $this->complete;
    }

    public function setComplete(bool $complete): self
    {
        $this->complete = $complete;

        return $this;
    }
}

src/Entity/TeamEntryList.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TeamEntryListRepository")
 */
class TeamEntryList
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Race", inversedBy="teamEntryLists")
     * @ORM\JoinColumn(nullable=false)
     */
    private $race_id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Team")
     * @ORM\JoinColumn(nullable=false)
     */
    private $team_id;

    /**
     * @ORM\Column(type="integer")
     */
    private $racenumber;

    /**
     * @ORM\Column(type="integer")
     */
    private $carmodel;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $result;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $bestlap;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $Laps;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRaceId(): ?Race
    {
        return $this->race_id;
    }

    public function setRaceId(?Race $race_id): self
    {
        $this->race_id = $race_id;

        return $this;
    }

    public function getTeamId(): ?Team
    {
        return $this->team_id;
    }

    public function setTeamId(?Team $team_id): self
    {
        $this->team_id = $team_id;

        return $this;
    }

    public function getResult(): ?int
    {
        return $this->result;
    }


    public function getRacenumber(): ?int
    {
        return $this->racenumber;
    }

    public function setRacenumber(int $racenumber): self
    {
        $this->racenumber = $racenumber;

        return $this;
    }

    public function getCarmodel(): ?int
    {
        return $this->carmodel;
    }

    public function setCarmodel(int $carmodel): self
    {
        $this->carmodel = $carmodel;

        return $this;
    }

    public function setResult(?int $result): self
    {
        $this->result = $result;

        return $this;
    }

    public function getBestlap(): ?int
    {
        return $this->bestlap;
    }

    public function setBestlap(?int $bestlap): self
    {
        $this->bestlap = $bestlap;

        return $this;
    }

    public function getLaps(): ?int
    {
        return $this->Laps;
    }

    public function setLaps(?int $Laps): self
    {
        $this->Laps = $Laps;

        return $this;
    }
}

src/Controller/HistoricController.php
<?php

namespace App\Controller;

use App\Entity\Championship;
use App\Entity\Race;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/historic", name="historic")
 */
class HistoricController extends AbstractController
{
    /**
     * @Route("/", name="_championships")
     */
    public function index()
    {
        $championships = $this->getDoctrine()->getRepository(Championship::class)->findAll();
        return $this->render("historic/index.html.twig", array('championships'=>$championships));
    }

    /**
     * @Route("/{id}", name="_races")
     */
    public function races($id)
    {
        $races = $this->getDoctrine()->getRepository(Championship::class)->find($id)->getRaces();
        return $this->render("historic/race.html.twig", array('races'=>$races));
    }

    /**
     * @Route("/race/{id}", name="_race")
     */
    public function race($id)
    {
        $race = $this->getDoctrine()->getRepository(Race::class)->find($id)->getTeamEntryLists();
        return $this->render("historic/result.html.twig", array('results'=>$race));
    }

    /**
     * @Route("/championship/{id}", name="_championship")
     */
    public function championships($id)
    {
        $championshipentries = $this->getDoctrine()->getRepository(Championship::class)->find($id)->getChampionshipEntries();
        return $this->render("historic/championship.html.twig", [
            'championshipentries' => $championshipentries
        ]);
    }
}

templates/historic/championship.html.twig
{% extends 'base.html.twig' %}
{% set championship = "" %}
{% set championshipid = 0 %}
{% for entry in championshipentries %}
    {% set championship = entry.championship.name %}
    {% set championshipid = entry.championship.id %}
{% endfor %}
{% block title %}RLM | {{ championship }} Standings{% endblock %}
{% block body %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb bg-light">
            <li class="breadcrumb-item">
                <a href="{{ path('user_home') }}">
                    Home
                </a>
            </li>
            <li class="breadcrumb-item">
                <a href="{{ path('historic_championships') }}">
                    Historic
                </a>
            </li>
            <li class="breadcrumb-item">
                <a href="{{ path('historic_races', {'id': championshipid}) }}">
                    {{ championship }}
                </a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">
                Standings
            </li>
        </ol>
    </nav>
    <table class="table table-striped table-borderless table-dark">
        <thead class="thead-dark">
        <tr>
            <th>Team Name</th>
            <th>Points</th>
        </tr>
        </thead>
        <tbody>
        {% for entry in championshipentries %}
            <tr>
                <td>
                    {{ entry.team.name }}
                </td>
                <td>
                    {{ entry.points }}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/historic/index.html.twig
{% extends 'base.html.twig' %}
{% block title %}RLM | Historic{% endblock %}
{% block body %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb bg-light">
            <li class="breadcrumb-item">
                <a href="{{ path('user_home') }}">
                    Home
                </a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">
                Historic
            </li>
        </ol>
    </nav>
    <ul class="list-group">
        {% for championship in championships %}
            <li class="list-group-item">
                <a href="{{ path('historic_races', {'id': championship.id })}}">
                    {{ championship.name }}
                </a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

templates/historic/race.html.twig
{% extends 'base.html.twig' %}
{% set championship = "" %}
{% set championshipid = 0 %}
{% for race in races %}
    {% set championship = race.championshipId.name %}
    {% set championshipid = race.championshipId.id %}
{% endfor %}
{% block title %}RLM | {{ championship }}{% endblock %}
{% block body %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb bg-light">
            <li class="breadcrumb-item">
                <a href="{{ path('user_home') }}">
                    Home
                </a>
            </li>
            <li class="breadcrumb-item">
                <a href="{{ path('historic_championships') }}">
                    Historic
                </a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">
                {{ championship }}
            </li>
        </ol>
    </nav>
    <table class="table table-striped table-borderless table-dark">
        <thead class="thead-light">
        <tr>
            <th>Circuit</th>
            <th>Free Practice Length</th>
            <th>Qualifying Length</th>
            <th>Race Length</th>
            <th>Results</th>
        </tr>
        </thead>
        <tbody>
        {% for race in races %}
            <tr>
                <td>
                    {{ race.track | replace({'_2019': ""}) | replace({'_': " "}) | title }}
                </td>
                <td>
                    {{ race.practiceLength }} minutes
                </td>
                <td>
                    {{ race.qualyLength }} minutes
                </td>
                <td>
                    {{ race.raceLength }} minutes
                </td>
                <td>
                    <a href="{{ path('historic_race', {'id': race.id })}}">
                        Results
                    </a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="row text-center">
        <div class="col">
            <a href="{{ path('historic_championship', {'id': championshipid }) }}" class="btn btn-info">
                See Championship Standings
            </a>
        </div>
    </div>
{% endblock %}

templates/historic/result.html.twig
{% extends 'base.html.twig' %}
{% block title %}RLM | Race Results {% endblock %}
{% set racename = "" %}
{% for result in results %}
    {% set racename = result.raceid.raceinfo %}
{% endfor %}
{% block body %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb bg-light">
            <li class="breadcrumb-item">
                <a href="{{ path('user_home') }}">
                    Home
                </a>
            </li>
            <li class="breadcrumb-item">
                <a href="{{ path('historic_championships') }}">
                    Historic
                </a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">
                {{ racename }}
            </li>
        </ol>
    </nav>
    <table class="table table-striped table-borderless table-dark">
        <thead class="thead-dark">
        <tr>
            <th>#</th>
            <th>Team Name</th>
            <th>Drivers</th>
            <th>Car</th>
            <th>Fastest Lap</th>
            <th>Race Length</th>
            <th>Laps</th>
        </tr>
        </thead>
        <tbody>
        {% for result in results %}
            <tr>
                <td>
                    {{ result.racenumber }}
                </td>
                <td>
                    {{ result.teamid.name }}
                </td>
                <td>
                    {% set driverstring = "" %}
                    {% for driver in result.teamid.teamDrivers %}
                        {% if driverstring == "" %}
                            {% set driverstring = driver.driver.__toString %}
                        {% else %}
                            {% set driverstring = [driverstring, ' / ' , driver.driver.__toString] | join %}
                        {% endif %}
                    {% endfor %}
                    {{ driverstring }}
                </td>
                <td>
                    {{ result.carmodel | replace({"0": "Porsche 991 GT3", "1": "Mercedes AMG GT3", "2": "Ferrari 488 GT3",
                        "3": "Audi R8 LMS", "4": "Lamborghini Huracan GT3", "5": "McLaren 650S GT3", "6": "Nissan GT-R Nismo GT3 2018",
                        "7": "BMW M6 GT3", "8": "Bentley Continental GT3 2018", "9": "Porsche 911.2 GT3 Cup",
                        "10": "Nissan GT-R Nismo GT3 2017", "11": "Bentley Continental GT3 2016", "12": "Aston Martin Vantage V12 GT3",
                        "13": "Lamborghini Gallardo R-EX", "14": "Jaguar G3", "15": "Lexus RC F GT3", "16": "Lamborghini Huracan Evo",
                        "17": "Honda NSX GT3", "18": "Lamborghini Huracan SuperTrofeo", "19": "Audi R8 LMS Evo",
                        "20": "Aston Martin Vantage V8", "21": "Honda NSX Evo", "22": "McLaren 720S GT3", "23": "Porsche 911 II GT3 R"}) }}
                </td>
                <td>
                    {% set ms = result.bestlap[-3:] %}
                    {% set seconds = result.bestlap[:-3] %}
                    {% set hours = seconds / 3600 % 60 %}
                    {% if hours  < 1 %}
                        {# set hours to nothing #}
                        {% set hours = null %}
                    {% else %}
                        {# output hours with a colon: #}
                        {% set hours = hours|number_format ~ ':' %}
                    {% endif %}
                    {# set minutes remain but no seconds and with a colon #}
                    {% set minutes = seconds / 60 % 60  ~ ':' %}
                    {# set seconds but no minutes or hours #}
                    {% set seconds = seconds % 60 %}
                    {% if seconds < 10 %}
                        {# add a leading zero if seconds are less than 10 #}
                        {% set seconds = '0' ~ seconds %}
                    {% endif %}
                    {% if hours != null %}{{ hours }}{% endif %}{{ minutes }}{{ seconds }}.{{ ms }}
                </td>
                <td>
                    {% set ms = result.result[-3:] %}
                    {% set seconds = result.result[:-3] %}
                    {% set hours = seconds / 3600 % 60 %}
                    {% if hours  < 1 %}
                        {# set hours to nothing #}
                        {% set hours = null %}
                    {% else %}
                        {# output hours with a colon: #}
                        {% set hours = hours|number_format ~ ':' %}
                    {% endif %}
                    {# set minutes remain but no seconds and with a colon #}
                    {% set minutes = seconds / 60 % 60 %}
                    {% if minutes < 10 %}
                        {# add a leading zero if minutes are less than 10 #}
                        {% set minutes = '0' ~ minutes %}
                    {% endif %}
                    {% set minutes = minutes ~ ':' %}
                    {# set seconds but no minutes or hours #}
                    {% set seconds = seconds % 60 %}
                    {% if seconds < 10 %}
                        {# add a leading zero if seconds are less than 10 #}
                        {% set seconds = '0' ~ seconds %}
                    {% endif %}
                    {% if hours != null %}{{ hours }}{% endif %}{{ minutes }}{{ seconds }}.{{ ms }}
                </td>
                <td>
                    {{ result.laps }}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <a href="{{ path('historic_championships') }}">Go Back</a>
{% endblock %}