src/Entity/Race.php
<?php

namespace App\Entity;

use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\RaceRepository")
 */
class Race
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=64)
     */
    private $track;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Championship", inversedBy="races")
     */
    private $championship_id;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\TeamEntryList", mappedBy="race_id")
     * @ORM\OrderBy({"Laps" = "DESC", "result" = "ASC"})
     */
    private $teamEntryLists;

    /**
     * @ORM\Column(type="integer")
     */
    private $ambientTemp;

    /**
     * @ORM\Column(type="float")
     */
    private $cloudLevel;

    /**
     * @ORM\Column(type="float")
     */
    private $rain;

    /**
     * @ORM\Column(type="integer")
     */
    private $practice_hour;

    /**
     * @ORM\Column(type="integer")
     */
    private $practice_length;

    /**
     * @ORM\Column(type="integer")
     */
    private $qualy_hour;

    /**
     * @ORM\Column(type="integer")
     */
    private $qualy_length;

    /**
     * @ORM\Column(type="integer")
     */
    private $race_hour;

    /**
     * @ORM\Column(type="integer")
     */
    private $race_length;

    /**
     * @ORM\Column(type="datetime")
     */
    private $greenflagtime;

    /**
     * @ORM\Column(type="boolean", options={"default": false})
     */
    private $complete;

    public function __construct()
    {
        $this->teamEntryLists = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTrack(): ?string
    {
        return $this->track;
    }

    public function setTrack(string $track): self
    {
        $this->track = $track;

        return $this;
    }

    public function getChampionshipId(): ?Championship
    {
        return $this->championship_id;
    }

    public function setChampionshipId(?Championship $championship_id): self
    {
        $this->championship_id = $championship_id;

        return $this;
    }

    /**
     * @return Collection|TeamEntryList[]
     */
    public function getTeamEntryLists(): Collection
    {
        return $this->teamEntryLists;
    }

    public function addTeamEntryList(TeamEntryList $teamEntryList): self
    {
        if (!$this->teamEntryLists->contains($teamEntryList)) {
            $this->teamEntryLists[] = $teamEntryList;
            $teamEntryList->setRaceId($this);
        }

        return $this;
    }

    public function removeTeamEntryList(TeamEntryList $teamEntryList): self
    {
        if ($this->teamEntryLists->contains($teamEntryList)) {
            $this->teamEntryLists->removeElement($teamEntryList);
            // set the owning side to null (unless already changed)
            if ($teamEntryList->getRaceId() === $this) {
                $teamEntryList->setRaceId(null);
            }
        }

        return $this;
    }

    public function getAmbientTemp(): ?int
    {
        return $this->ambientTemp;
    }

    public function setAmbientTemp(int $ambientTemp): self
    {
        $this->ambientTemp = $ambientTemp;

        return $this;
    }

    public function getCloudLevel(): ?float
    {
        return $this->cloudLevel;
    }

    public function setCloudLevel(float $cloudLevel): self
    {
        $this->cloudLevel = $cloudLevel;

        return $this;
    }

    public function getRain(): ?float
    {
        return $this->rain;
    }

    public function setRain(float $rain): self
    {
        $this->rain = $rain;

        return $this;
    }

    public function getPracticeHour(): ?int
    {
        return $this->practice_hour;
    }

    public function setPracticeHour(int $practice_hour): self
    {
        $this->practice_hour = $practice_hour;

        return $this;
    }

    public function getPracticeLength(): ?int
    {
        return $this->practice_length;
    }

    public function setPracticeLength(int $practice_length): self
    {
        $this->practice_length = $practice_length;

        return $this;
    }

    public function getQualyHour(): ?int
    {
        return $this->qualy_hour;
    }

    public function setQualyHour(int $qualy_hour): self
    {
        $this->qualy_hour = $qualy_hour;

        return $this;
    }

    public function getQualyLength(): ?int
    {
        return $this->qualy_length;
    }

    public function setQualyLength(int $qualy_length): self
    {
        $this->qualy_length = $qualy_length;

        return $this;
    }

    public function getRaceHour(): ?int
    {
        return $this->race_hour;
    }

    public function setRaceHour(int $race_hour): self
    {
        $this->race_hour = $race_hour;

        return $this;
    }

    public function getRaceLength(): ?int
    {
        return $this->race_length;
    }

    public function setRaceLength(int $race_length): self
    {
        $this->race_length = $race_length;

        return $this;
    }

    public function getGreenflagtime(): ?DateTimeInterface
    {
        return $this->greenflagtime;
    }

    public function setGreenflagtime(DateTimeInterface $greenflagtime): self
    {
        $this->greenflagtime = $greenflagtime;

        return $this;
    }

    /**
     * This function obtains a formatted name to easily identify a race, with the following format:
     * Race Track - Championship Name
     * @return string String formatted to easily identify which Race it is.
     */
    public function getRaceinfo(): string
    {
        $string = "";
        $string = $string.$this->getTrack();
        $string = $string.' - '.$this->getChampionshipId()->getName();
        $string = str_replace('_2019', '', $string);
        $string = str_replace('_', ' ', $string);
        return ucwords($string);
    }

    public function getComplete(): ?bool
    {
        return $this->complete;
    }

    public function setComplete(bool $complete): self
    {
        $this->complete = $complete;

        return $this;
    }
}

src/Entity/TeamEntryList.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TeamEntryListRepository")
 */
class TeamEntryList
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Race", inversedBy="teamEntryLists")
     * @ORM\JoinColumn(nullable=false)
     */
    private $race_id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Team")
     * @ORM\JoinColumn(nullable=false)
     */
    private $team_id;

    /**
     * @ORM\Column(type="integer")
     */
    private $racenumber;

    /**
     * @ORM\Column(type="integer")
     */
    private $carmodel;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $result;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $bestlap;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $Laps;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRaceId(): ?Race
    {
        return $this->race_id;
    }

    public function setRaceId(?Race $race_id): self
    {
        $this->race_id = $race_id;

        return $this;
    }

    public function getTeamId(): ?Team
    {
        return $this->team_id;
    }

    public function setTeamId(?Team $team_id): self
    {
        $this->team_id = $team_id;

        return $this;
    }

    public function getResult(): ?int
    {
        return $this->result;
    }


    public function getRacenumber(): ?int
    {
        return $this->racenumber;
    }

    public function setRacenumber(int $racenumber): self
    {
        $this->racenumber = $racenumber;

        return $this;
    }

    public function getCarmodel(): ?int
    {
        return $this->carmodel;
    }

    public function setCarmodel(int $carmodel): self
    {
        $this->carmodel = $carmodel;

        return $this;
    }

    public function setResult(?int $result): self
    {
        $this->result = $result;

        return $this;
    }

    public function getBestlap(): ?int
    {
        return $this->bestlap;
    }

    public function setBestlap(?int $bestlap): self
    {
        $this->bestlap = $bestlap;

        return $this;
    }

    public function getLaps(): ?int
    {
        return $this->Laps;
    }

    public function setLaps(?int $Laps): self
    {
        $this->Laps = $Laps;

        return $this;
    }
}

src/Controller/RaceController.php
<?php

namespace App\Controller;

use App\Entity\Championship;
use App\Entity\Race;
use App\Entity\TeamEntryList;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Process\Process;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Security("is_granted('ROLE_ADMIN')")
 * @Route("/races", name="race")
 */
class RaceController extends AbstractController
{
    /**
     * @Route("/dashboard", name="_dashboard")
     */
    public function index(): Response
    {
        $championships = $this->getDoctrine()->getRepository(Championship::class)->findAll();
        return $this->render('race/index.html.twig', [
            'championships' => $championships,
        ]);
    }
    /**
     * @Route("/champ/{id}", name="_champ")
     */
    public function champInfo($id): Response
    {
        $races = $this->getDoctrine()->getRepository(Championship::class)->find($id)->getRaces();
        return $this->render("race/race.html.twig", array('races'=>$races));
    }
    /**
     * @Route("/race/{id}", name="_info")
     */
    public function raceInfo($id): Response
    {
        $race = $this->getDoctrine()->getRepository(Race::class)->find($id);
        return $this->render("race/info.html.twig", array('race'=>$race, 'entrylist'=>$race->getTeamEntryLists()));
    }

    /**
     * @Route("/entrylist/{id}", name="_entrylist")
     */
    public function createEntryList($id): Response
    {
        $race = $this->getDoctrine()->getRepository(Race::class)->find($id);
        $entrylist = $race->getTeamEntryLists();
        $this->generateEntrylist($entrylist);
        return $this->render("race/info.html.twig", array('race'=>$race, 'entrylist'=>$entrylist));
    }

    /**
     * @Route("/launch/{id}", name="_launch")
     */
    public function launchServer($id): Response
    {
        $race = $this->getDoctrine()->getRepository(Race::class)->find($id);
        $message = 'The race server for '.$race->getChampionshipId()->getName().' at '.ucwords(str_replace('_', ' ', str_replace('_2019', '', $race->getTrack()))).' has been launched.';
        $entrylist = $race->getTeamEntryLists();
        $this->generateEntrylist($entrylist);
        $process = new Process([$_SERVER['APP_FOLDER'].'\\accServer.exe', $_SERVER['APP_FOLDER']]);
        $process->setTimeout($this->calculateTimeout($race));
        //if ($_ENV['APP_ENV'] == 'dev') $process->start();
        return $this->render('admin/server.html.twig', [
            'message' => $message,
            'race' => $race
        ]);
    }

    /**
     * This function generates an entrylist.json based on the entrylists given.
     * @param TeamEntryList[] $entrylist Array with Entrylists
     */
    private function generateEntrylist($entrylist): void
    {
        $entrylist_json = '{"entries":[';
        foreach ($entrylist as $entry) {
            $teamdrivers = $entry->getTeamId()->getTeamDrivers();
            $entrylist_json = $entrylist_json.'{"drivers":[';
            $drivercount = 0;
            foreach ($teamdrivers as $driver) {
                $entrylist_json = $drivercount == 0 ? $entrylist_json.
                    '{"firstName":"' . $driver->getDriver()->getName() . '", "lastName": "' .$driver->getDriver()->getLastname() . '", "playerID": "S' . $driver->getDriver()->getSteamid() . '"}' : $entrylist_json . ',{"firstName":"' . $driver->getDriver()->getName() . '", "lastName": "' . $driver->getDriver()->getLastname() . '", "playerID": "S' . $driver->getDriver()->getSteamid() . '"}';
                $drivercount++;
            }
            $entrylist_json = $entrylist_json.'],"raceNumber":'.$entry->getRacenumber().',';
            $entrylist_json = $entrylist_json.'"forcedCarModel":'.$entry->getCarmodel();
            if (!next($entrylist)) {
                $entrylist_json = $entrylist_json . '}';
            } else {
                $entrylist_json = $entrylist_json . '},';
            }
        }
        $entrylist_json = $entrylist_json.'], "forceEntryList": 1}';
        $filepath = $_SERVER['APP_FOLDER']."\cfg\\entrylist.json";
        file_put_contents($filepath, $entrylist_json);
    }

    private function calculateTimeout(Race $race): int
    {
        $result = 0;
        $result += $race->getPracticeLength()*60;
        $result += $race->getQualyLength()*60;
        $result += $race->getRaceLength()*60;
        return $result;
    }
}

templates/race/index.html.twig
{% extends 'base.html.twig' %}
{% block title %}RLM | Race Information{% endblock %}
{% block body %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb bg-light">
            <li class="breadcrumb-item">
                <a href="{{ path('user_home') }}">
                    Home
                </a>
            </li>
            <li class="breadcrumb-item">
                <a href="{{ path('admin_home') }}">
                    Admin
                </a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">
                Races Info
            </li>
        </ol>
    </nav>
    <ul class="list-group">
        {% for championship in championships %}
            <li class="list-group-item">
                <a href="{{ path('race_champ', {'id': championship.id })}}">
                    {{ championship.name }}
                </a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

templates/race/info.html.twig
{% extends 'base.html.twig' %}
{% block title %}RLM | Race Info{% endblock %}
{% block body %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb bg-light">
            <li class="breadcrumb-item">
                <a href="{{ path('user_home') }}">
                    Home
                </a>
            </li>
            <li class="breadcrumb-item">
                <a href="{{ path('admin_home') }}">
                    Admin
                </a>
            </li>
            <li class="breadcrumb-item">
                <a href="{{ path('race_champ', {'id': race.championshipId.id}) }}">
                    {{ race.championshipId.name }}
                </a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">
                {{ race.track | replace({'_2019': ""}) | replace({'_': " "}) | title }}
            </li>
        </ol>
    </nav>
    <div class="card text-dark">
        <img src="{{ asset(['img/tracks/', race.track | replace({'_2019': ""}), '.png'] | join) }}"
             class="card-img-top" alt="{{ race.track | replace({'_2019': ""}) | replace({'_': " "}) | title }}"
             style="max-width: 50%; display: block; margin:auto">
        <div class="card-body">
            <h5 class="card-title">{{ race.track | replace({'_2019': ""}) | replace({'_': " "}) | title }}</h5>
            <p class="card-text">Length: {{ race.raceLength }} Minutes</p>
        </div>
        {% if entrylist | length != 0 %}
            <ul class="list-group list-group-flush">
                <li class="list-group-item">Entrylist: Team Name | Race #</li>
                {% for entry in entrylist %}
                    <li class="list-group-item">{{ entry.teamId.name }} | {{ entry.racenumber }}</li>
                {% endfor %}
            </ul>
        {% endif %}
        <div class="card-body">
            <a href="{{ path('race_launch', {'id': race.id}) }}">
                Launch Server - Security Risk (Only runs on Dev environments)
            </a>
            <a href="{{ path('race_entrylist', {'id': race.id }) }}">
                Generate JSON of Entrylist
            </a>
        </div>
    </div>
{% endblock %}

templates/race/race.html.twig
{% extends 'base.html.twig' %}
{% set championship = "" %}
{% set championshipid = 0 %}
{% for race in races %}
    {% set championship = race.championshipId.name %}
    {% set championshipid = race.championshipId.id %}
{% endfor %}
{% block title %}RLM | {{ championship }} Info{% endblock %}
{% block body %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb bg-light">
            <li class="breadcrumb-item">
                <a href="{{ path('user_home') }}">
                    Home
                </a>
            </li>
            <li class="breadcrumb-item">
                <a href="{{ path('admin_home') }}">
                    Admin
                </a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">
                {{ championship }}
            </li>
        </ol>
    </nav>
    <table class="table table-striped table-borderless table-dark">
        <thead class="thead-dark">
            <tr>
                <th>
                    Circuit
                </th>
                <th>
                    Free Practice Length
                </th>
                <th>
                    Qualifying Length
                </th>
                <th>
                    Race Length
                </th>
                <th>
                    Info
                </th>
            </tr>
        </thead>
        <tbody>
        {% for race in races %}
            {% if race.complete != true %}
            <tr>
                <td>
                    {{ race.track | replace({'_2019': ""}) | replace({'_': " "}) | title }}
                </td>
                <td>
                    {{ race.practiceLength }} minutes
                </td>
                <td>
                    {{ race.qualyLength }} minutes
                </td>
                <td>
                    {{ race.raceLength }} minutes
                </td>
                <td>
                    <a href="{{ path('race_info', {'id': race.id })}}">
                        Info
                    </a>
                </td>
            </tr>
            {% endif %}
        {% endfor %}
        </tbody>
    </table>
    <a href="{{ path('race_dashboard') }}">Go Back to Championships</a>
{% endblock %}